In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)  # 检查版本
print(torch.cuda.is_available())  # 检查 CUDA 是否可用
print(torch.version.cuda)  # 检查 CUDA 版本

2.6.0+cu118
True
11.8


### Tensors

In [11]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [ ]:
vector.shape    

torch.Size([2])

In [9]:
#Matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

### Random Tensors

In [14]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1784, 0.1631, 0.9464, 0.4995],
        [0.2052, 0.8446, 0.6548, 0.5433],
        [0.9190, 0.7610, 0.2025, 0.0751]])

In [16]:
random_image_size_tensor = torch.rand(size = (224, 224, 3)) #height, width, color channals (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [18]:
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones = torch.ones(size = (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

### Creating a Range of Tensors and Tensors-like

In [ ]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
one_to_twenty = torch.arange(start = 1, end = 21, step = 1)
one_to_twenty

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])

In [28]:
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [29]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, 
                               device = None,
                               requires_grad = False)
float_32_tensor

tensor([3., 6., 9.])